### ISSUE TITLE
Does Async Storage Get Deleted when the App is Closed? 

### ISSUE THREAD

**Issue by thekennysong** [thewei/react-native-store#8]
I was wondering if it gets deleted once the app is closed? Because then I feel like using sqlite is a better option.

**Comment by thewei** [comment]
Async Strorage can keep the data when the app closed. lt is a simple database.

**Comment by andrei-cacio** [comment]
@thewei I am trying to achieve the same thing with AsyncStorage. How can I keep my data after the app closes?

Thanks!
Andrei

**Comment by Bharavi26** [comment]
same issue ...when i save data with AsyncStorage and when i close app from background and after it when m getting data from AsyncStorage it cleared....

**Comment by hugoskn** [comment]
Same issue here, can someone advise on this? BTW my app is created with expo/snack

**Comment by sun21170** [comment]
I'm also seeing the same issue with an expo react native app running on my android device. When I open the app, login successfully then user token gets stored in async storage, but when I close the app window and re-open the app from Expo client then the user token stored in async storage is no more there. The Expo client is kept open during all these steps.

**UPDATE**
I found that the problem was with my Login component code  and not with async storage. In the code it was not setting initial state based on async storage user token when Login component first rendered. Once I included state initialization code in Login component, then even after closing Expo client and the re-opening the app, I did not see the login screen since user token was already stored in async storage before the app was closed and re-opened.

Even when I shut down my android device and restarted it, the expo react native app when opened did not show the login screen since user token was there in async storage.

**So, async storage works as expected and provides persistent storage as expected .**

**Comment by ericscottmarquez** [comment]
> I'm also seeing the same issue with an expo react native app running on my android device. When I open the app, login successfully then user token gets stored in async storage, but when I close the app window and re-open the app from Expo client then the user token stored in async storage is no more there. The Expo client is kept open during all these steps.
> 
> **UPDATE**
> I found that the problem was with my Login component code and not with async storage. In the code it was not setting initial state based on async storage user token when Login component first rendered. Once I included state initialization code in Login component, then even after closing Expo client and the re-opening the app, I did not see the login screen since user token was already stored in async storage before the app was closed and re-opened.
> 
> Even when I shut down my android device and restarted it, the expo react native app when opened did not show the login screen since user token was there in async storage.
> 
> **So, async storage works as expected and provides persistent storage as expected .**

@sun21170 How did you get the expo client to keep persistent storage? I have tried ```const user = await AsyncStorage.getItem('currentUser');``` in `componentDidMount()` in the index of the app but it still doesn't load the data after closing expo and reopening the app (qr code with metro bundler)
